[project]
name = "starknights-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Akhir Alibhai", email = "akhir.alibhai@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "discord-py[voice]>=2.7.1",
]

[project.scripts]
starknights-bot = "starknights_bot:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
